// src/app/layout.js
import { Montserrat } from "next/font/google";
import "./globals.css";

// Importa Montserrat desde Google Fonts
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"], // Agrega los pesos que necesites
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        {children}
      </body>
    </html>
  );
}
